// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { File, FileT } from './file.js';


export class Files implements flatbuffers.IUnpackableObject<FilesT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Files {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFiles(bb:flatbuffers.ByteBuffer, obj?:Files):Files {
  return (obj || new Files()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFiles(bb:flatbuffers.ByteBuffer, obj?:Files):Files {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Files()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

records(index: number, obj?:File):File|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new File()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

recordsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startFiles(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRecords(builder:flatbuffers.Builder, recordsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, recordsOffset, 0);
}

static createRecordsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRecordsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endFiles(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishFilesBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedFilesBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createFiles(builder:flatbuffers.Builder, recordsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Files.startFiles(builder);
  Files.addRecords(builder, recordsOffset);
  return Files.endFiles(builder);
}

unpack(): FilesT {
  return new FilesT(
    this.bb!.createObjList<File, FileT>(this.records.bind(this), this.recordsLength())
  );
}


unpackTo(_o: FilesT): void {
  _o.records = this.bb!.createObjList<File, FileT>(this.records.bind(this), this.recordsLength());
}
}

export class FilesT implements flatbuffers.IGeneratedObject {
constructor(
  public records: (FileT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const records = Files.createRecordsVector(builder, builder.createObjectOffsetList(this.records));

  return Files.createFiles(builder,
    records
  );
}
}
