// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class File implements flatbuffers.IUnpackableObject<FileT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):File {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFile(bb:flatbuffers.ByteBuffer, obj?:File):File {
  return (obj || new File()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFile(bb:flatbuffers.ByteBuffer, obj?:File):File {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new File()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nrInst():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mutate_nrInst(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

nrAgencia():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mutate_nrAgencia(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

cdClient():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mutate_cdClient(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

nmClient():string|null
nmClient(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
nmClient(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

nrCpfCnpj():string|null
nrCpfCnpj(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
nrCpfCnpj(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

nrContrato():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mutate_nrContrato(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

dtContrato():string|null
dtContrato(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
dtContrato(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

qtPrestacoes():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mutate_qtPrestacoes(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 18);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

vlTotal():string|null
vlTotal(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vlTotal(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

cdProduto():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mutate_cdProduto(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

dsProduto():string|null
dsProduto(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
dsProduto(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

cdCarteira():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mutate_cdCarteira(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 26);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

dsCarteira():string|null
dsCarteira(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
dsCarteira(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

nrProposta():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mutate_nrProposta(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 30);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

nrPresta():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mutate_nrPresta(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 32);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

tpPresta():string|null
tpPresta(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
tpPresta(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

nrSeqPre():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mutate_nrSeqPre(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 36);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

dtVctPre():string|null
dtVctPre(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
dtVctPre(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

vlPresta():string|null
vlPresta(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vlPresta(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

vlMora():string|null
vlMora(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vlMora(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

vlMulta():string|null
vlMulta(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vlMulta(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

vlOutAcr():string|null
vlOutAcr(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vlOutAcr(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

vlIof():string|null
vlIof(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vlIof(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

vlDescon():string|null
vlDescon(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vlDescon(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

vlAtual():string|null
vlAtual(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vlAtual(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

idSituac():string|null
idSituac(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
idSituac(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

idSitVen():string|null
idSitVen(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
idSitVen(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sitVal():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

mutate_sitVal(value:boolean):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 58);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt8(this.bb_pos + offset, +value);
  return true;
}

static startFile(builder:flatbuffers.Builder) {
  builder.startObject(28);
}

static addNrInst(builder:flatbuffers.Builder, nrInst:number) {
  builder.addFieldInt32(0, nrInst, 0);
}

static addNrAgencia(builder:flatbuffers.Builder, nrAgencia:number) {
  builder.addFieldInt32(1, nrAgencia, 0);
}

static addCdClient(builder:flatbuffers.Builder, cdClient:number) {
  builder.addFieldInt32(2, cdClient, 0);
}

static addNmClient(builder:flatbuffers.Builder, nmClientOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, nmClientOffset, 0);
}

static addNrCpfCnpj(builder:flatbuffers.Builder, nrCpfCnpjOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, nrCpfCnpjOffset, 0);
}

static addNrContrato(builder:flatbuffers.Builder, nrContrato:number) {
  builder.addFieldInt32(5, nrContrato, 0);
}

static addDtContrato(builder:flatbuffers.Builder, dtContratoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, dtContratoOffset, 0);
}

static addQtPrestacoes(builder:flatbuffers.Builder, qtPrestacoes:number) {
  builder.addFieldInt32(7, qtPrestacoes, 0);
}

static addVlTotal(builder:flatbuffers.Builder, vlTotalOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, vlTotalOffset, 0);
}

static addCdProduto(builder:flatbuffers.Builder, cdProduto:number) {
  builder.addFieldInt32(9, cdProduto, 0);
}

static addDsProduto(builder:flatbuffers.Builder, dsProdutoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, dsProdutoOffset, 0);
}

static addCdCarteira(builder:flatbuffers.Builder, cdCarteira:number) {
  builder.addFieldInt32(11, cdCarteira, 0);
}

static addDsCarteira(builder:flatbuffers.Builder, dsCarteiraOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, dsCarteiraOffset, 0);
}

static addNrProposta(builder:flatbuffers.Builder, nrProposta:number) {
  builder.addFieldInt32(13, nrProposta, 0);
}

static addNrPresta(builder:flatbuffers.Builder, nrPresta:number) {
  builder.addFieldInt32(14, nrPresta, 0);
}

static addTpPresta(builder:flatbuffers.Builder, tpPrestaOffset:flatbuffers.Offset) {
  builder.addFieldOffset(15, tpPrestaOffset, 0);
}

static addNrSeqPre(builder:flatbuffers.Builder, nrSeqPre:number) {
  builder.addFieldInt32(16, nrSeqPre, 0);
}

static addDtVctPre(builder:flatbuffers.Builder, dtVctPreOffset:flatbuffers.Offset) {
  builder.addFieldOffset(17, dtVctPreOffset, 0);
}

static addVlPresta(builder:flatbuffers.Builder, vlPrestaOffset:flatbuffers.Offset) {
  builder.addFieldOffset(18, vlPrestaOffset, 0);
}

static addVlMora(builder:flatbuffers.Builder, vlMoraOffset:flatbuffers.Offset) {
  builder.addFieldOffset(19, vlMoraOffset, 0);
}

static addVlMulta(builder:flatbuffers.Builder, vlMultaOffset:flatbuffers.Offset) {
  builder.addFieldOffset(20, vlMultaOffset, 0);
}

static addVlOutAcr(builder:flatbuffers.Builder, vlOutAcrOffset:flatbuffers.Offset) {
  builder.addFieldOffset(21, vlOutAcrOffset, 0);
}

static addVlIof(builder:flatbuffers.Builder, vlIofOffset:flatbuffers.Offset) {
  builder.addFieldOffset(22, vlIofOffset, 0);
}

static addVlDescon(builder:flatbuffers.Builder, vlDesconOffset:flatbuffers.Offset) {
  builder.addFieldOffset(23, vlDesconOffset, 0);
}

static addVlAtual(builder:flatbuffers.Builder, vlAtualOffset:flatbuffers.Offset) {
  builder.addFieldOffset(24, vlAtualOffset, 0);
}

static addIdSituac(builder:flatbuffers.Builder, idSituacOffset:flatbuffers.Offset) {
  builder.addFieldOffset(25, idSituacOffset, 0);
}

static addIdSitVen(builder:flatbuffers.Builder, idSitVenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(26, idSitVenOffset, 0);
}

static addSitVal(builder:flatbuffers.Builder, sitVal:boolean) {
  builder.addFieldInt8(27, +sitVal, +false);
}

static endFile(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFile(builder:flatbuffers.Builder, nrInst:number, nrAgencia:number, cdClient:number, nmClientOffset:flatbuffers.Offset, nrCpfCnpjOffset:flatbuffers.Offset, nrContrato:number, dtContratoOffset:flatbuffers.Offset, qtPrestacoes:number, vlTotalOffset:flatbuffers.Offset, cdProduto:number, dsProdutoOffset:flatbuffers.Offset, cdCarteira:number, dsCarteiraOffset:flatbuffers.Offset, nrProposta:number, nrPresta:number, tpPrestaOffset:flatbuffers.Offset, nrSeqPre:number, dtVctPreOffset:flatbuffers.Offset, vlPrestaOffset:flatbuffers.Offset, vlMoraOffset:flatbuffers.Offset, vlMultaOffset:flatbuffers.Offset, vlOutAcrOffset:flatbuffers.Offset, vlIofOffset:flatbuffers.Offset, vlDesconOffset:flatbuffers.Offset, vlAtualOffset:flatbuffers.Offset, idSituacOffset:flatbuffers.Offset, idSitVenOffset:flatbuffers.Offset, sitVal:boolean):flatbuffers.Offset {
  File.startFile(builder);
  File.addNrInst(builder, nrInst);
  File.addNrAgencia(builder, nrAgencia);
  File.addCdClient(builder, cdClient);
  File.addNmClient(builder, nmClientOffset);
  File.addNrCpfCnpj(builder, nrCpfCnpjOffset);
  File.addNrContrato(builder, nrContrato);
  File.addDtContrato(builder, dtContratoOffset);
  File.addQtPrestacoes(builder, qtPrestacoes);
  File.addVlTotal(builder, vlTotalOffset);
  File.addCdProduto(builder, cdProduto);
  File.addDsProduto(builder, dsProdutoOffset);
  File.addCdCarteira(builder, cdCarteira);
  File.addDsCarteira(builder, dsCarteiraOffset);
  File.addNrProposta(builder, nrProposta);
  File.addNrPresta(builder, nrPresta);
  File.addTpPresta(builder, tpPrestaOffset);
  File.addNrSeqPre(builder, nrSeqPre);
  File.addDtVctPre(builder, dtVctPreOffset);
  File.addVlPresta(builder, vlPrestaOffset);
  File.addVlMora(builder, vlMoraOffset);
  File.addVlMulta(builder, vlMultaOffset);
  File.addVlOutAcr(builder, vlOutAcrOffset);
  File.addVlIof(builder, vlIofOffset);
  File.addVlDescon(builder, vlDesconOffset);
  File.addVlAtual(builder, vlAtualOffset);
  File.addIdSituac(builder, idSituacOffset);
  File.addIdSitVen(builder, idSitVenOffset);
  File.addSitVal(builder, sitVal);
  return File.endFile(builder);
}

unpack(): FileT {
  return new FileT(
    this.nrInst(),
    this.nrAgencia(),
    this.cdClient(),
    this.nmClient(),
    this.nrCpfCnpj(),
    this.nrContrato(),
    this.dtContrato(),
    this.qtPrestacoes(),
    this.vlTotal(),
    this.cdProduto(),
    this.dsProduto(),
    this.cdCarteira(),
    this.dsCarteira(),
    this.nrProposta(),
    this.nrPresta(),
    this.tpPresta(),
    this.nrSeqPre(),
    this.dtVctPre(),
    this.vlPresta(),
    this.vlMora(),
    this.vlMulta(),
    this.vlOutAcr(),
    this.vlIof(),
    this.vlDescon(),
    this.vlAtual(),
    this.idSituac(),
    this.idSitVen(),
    this.sitVal()
  );
}


unpackTo(_o: FileT): void {
  _o.nrInst = this.nrInst();
  _o.nrAgencia = this.nrAgencia();
  _o.cdClient = this.cdClient();
  _o.nmClient = this.nmClient();
  _o.nrCpfCnpj = this.nrCpfCnpj();
  _o.nrContrato = this.nrContrato();
  _o.dtContrato = this.dtContrato();
  _o.qtPrestacoes = this.qtPrestacoes();
  _o.vlTotal = this.vlTotal();
  _o.cdProduto = this.cdProduto();
  _o.dsProduto = this.dsProduto();
  _o.cdCarteira = this.cdCarteira();
  _o.dsCarteira = this.dsCarteira();
  _o.nrProposta = this.nrProposta();
  _o.nrPresta = this.nrPresta();
  _o.tpPresta = this.tpPresta();
  _o.nrSeqPre = this.nrSeqPre();
  _o.dtVctPre = this.dtVctPre();
  _o.vlPresta = this.vlPresta();
  _o.vlMora = this.vlMora();
  _o.vlMulta = this.vlMulta();
  _o.vlOutAcr = this.vlOutAcr();
  _o.vlIof = this.vlIof();
  _o.vlDescon = this.vlDescon();
  _o.vlAtual = this.vlAtual();
  _o.idSituac = this.idSituac();
  _o.idSitVen = this.idSitVen();
  _o.sitVal = this.sitVal();
}
}

export class FileT implements flatbuffers.IGeneratedObject {
constructor(
  public nrInst: number = 0,
  public nrAgencia: number = 0,
  public cdClient: number = 0,
  public nmClient: string|Uint8Array|null = null,
  public nrCpfCnpj: string|Uint8Array|null = null,
  public nrContrato: number = 0,
  public dtContrato: string|Uint8Array|null = null,
  public qtPrestacoes: number = 0,
  public vlTotal: string|Uint8Array|null = null,
  public cdProduto: number = 0,
  public dsProduto: string|Uint8Array|null = null,
  public cdCarteira: number = 0,
  public dsCarteira: string|Uint8Array|null = null,
  public nrProposta: number = 0,
  public nrPresta: number = 0,
  public tpPresta: string|Uint8Array|null = null,
  public nrSeqPre: number = 0,
  public dtVctPre: string|Uint8Array|null = null,
  public vlPresta: string|Uint8Array|null = null,
  public vlMora: string|Uint8Array|null = null,
  public vlMulta: string|Uint8Array|null = null,
  public vlOutAcr: string|Uint8Array|null = null,
  public vlIof: string|Uint8Array|null = null,
  public vlDescon: string|Uint8Array|null = null,
  public vlAtual: string|Uint8Array|null = null,
  public idSituac: string|Uint8Array|null = null,
  public idSitVen: string|Uint8Array|null = null,
  public sitVal: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const nmClient = (this.nmClient !== null ? builder.createString(this.nmClient!) : 0);
  const nrCpfCnpj = (this.nrCpfCnpj !== null ? builder.createString(this.nrCpfCnpj!) : 0);
  const dtContrato = (this.dtContrato !== null ? builder.createString(this.dtContrato!) : 0);
  const vlTotal = (this.vlTotal !== null ? builder.createString(this.vlTotal!) : 0);
  const dsProduto = (this.dsProduto !== null ? builder.createString(this.dsProduto!) : 0);
  const dsCarteira = (this.dsCarteira !== null ? builder.createString(this.dsCarteira!) : 0);
  const tpPresta = (this.tpPresta !== null ? builder.createString(this.tpPresta!) : 0);
  const dtVctPre = (this.dtVctPre !== null ? builder.createString(this.dtVctPre!) : 0);
  const vlPresta = (this.vlPresta !== null ? builder.createString(this.vlPresta!) : 0);
  const vlMora = (this.vlMora !== null ? builder.createString(this.vlMora!) : 0);
  const vlMulta = (this.vlMulta !== null ? builder.createString(this.vlMulta!) : 0);
  const vlOutAcr = (this.vlOutAcr !== null ? builder.createString(this.vlOutAcr!) : 0);
  const vlIof = (this.vlIof !== null ? builder.createString(this.vlIof!) : 0);
  const vlDescon = (this.vlDescon !== null ? builder.createString(this.vlDescon!) : 0);
  const vlAtual = (this.vlAtual !== null ? builder.createString(this.vlAtual!) : 0);
  const idSituac = (this.idSituac !== null ? builder.createString(this.idSituac!) : 0);
  const idSitVen = (this.idSitVen !== null ? builder.createString(this.idSitVen!) : 0);

  return File.createFile(builder,
    this.nrInst,
    this.nrAgencia,
    this.cdClient,
    nmClient,
    nrCpfCnpj,
    this.nrContrato,
    dtContrato,
    this.qtPrestacoes,
    vlTotal,
    this.cdProduto,
    dsProduto,
    this.cdCarteira,
    dsCarteira,
    this.nrProposta,
    this.nrPresta,
    tpPresta,
    this.nrSeqPre,
    dtVctPre,
    vlPresta,
    vlMora,
    vlMulta,
    vlOutAcr,
    vlIof,
    vlDescon,
    vlAtual,
    idSituac,
    idSitVen,
    this.sitVal
  );
}
}
